---
services:
  wrt-sdk-build:
    build:
      context: .
      args:
        WRT_VER: "24.10.0"
    container_name: wrt-sdk-build
    volumes:
      - ./out:/out
      - ./files:/files
    command: >
      bash -c '
        set +e
        export MAKEFLAGS="-j`nproc` V=s"
        cp -v /files/ramips-mt7621-defconfig-no-llvm.config /build/openwrt/.config
        make clean defconfig download world
        time make
        cp bin/targets/*/*/openwrt-sdk-*.tar.* /out
        echo "[INFO] DONE"
      '
